### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by sjtupingjian** [ethereum/py-solc#46]
* `py-solc` Version: 2.1.0
* `solc` Version:  0.4.17
* Python Version: 3.6
* OS: win

### What was wrong?
I try to compile a contract like this:
```
import json
import web3
import sys

from solc import compile_standard,compile_source,compile_files, link_code
from web3.contract import ConciseContract

compile_standard({'language': 'Solidity','sources': 'MetaCoin.sol'})

```
Executing this function returns an error:
```
Traceback (most recent call last):
  File "C:/Users/com/PycharmProjects/test/testCompile.py", line 35, in <module>
    compiled_sol = compile_source(contract_source_code)
  File "C:\Users\com\PycharmProjects\test\venv\lib\site-packages\solc\main.py", line 106, in compile_source
    stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
  File "C:\Users\com\PycharmProjects\test\venv\lib\site-packages\solc\utils\string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "C:\Users\com\PycharmProjects\test\venv\lib\site-packages\solc\wrapper.py", line 155, in solc_wrapper
    stderr=subprocess.PIPE)
  File "D:\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
How can I fix it?

#### Cute Animal Picture

> put a cute animal picture here.
![default](https://user-images.githubusercontent.com/34638201/37904508-9891eac4-312e-11e8-8394-27199b887d05.png)

**Comment by dylanjw** [comment]
Can you add some checks for the solc executable and the path file? e.g.:

```
import os
source_path = 'MetaCoin.sol'
if not os.path.exists(source_path):
    raise FileNotFoundError("No solidity file at path: {0}".format(os.path.realpath(source_path)) 
if not os.path.exists('solc'):
    raise FileNotFoundError("solc executable not found.  Is solc installed?")
```

**Comment by sjtupingjian** [comment]
Thanks for reply!

It returns error:
```
Traceback (most recent call last):
  File "C:/Users/com/PycharmProjects/test/testCompile.py", line 17, in <module>
    raise FileNotFoundError("solc executable not found.  Is solc installed?")
FileNotFoundError: solc executable not found.  Is solc installed?
```
I am still confused because the solc compiler was installed and it does work in commandline:
```
C:\Users\com>solcjs --help
Usage: AppData\Roaming\npm\node_modules\solc\solcjs [options] [input_file...]

Options:
  --version         Show version number                                [boolean]

  --optimize        Enable bytecode optimizer.                         [boolean]

  --bin             Binary of the contracts in hex.                    [boolean]

  --abi             ABI of the contracts.                              [boolean]

  --standard-json   Turn on Standard JSON Input / Output mode.         [boolean]

  --output-dir, -o  Output directory for the contracts.                 [string]

  --help            Show help                                          [boolean]
```

**Comment by dylanjw** [comment]
the solcjs package only gives the solc binary embedded in a js file behind js bindings.  It wont work for py-solc, which requires the solc binary to be in the executable path.

Unfortunately the handy py-solc installer helper does not work on windows: 

```
$ python -m solc.install v0.4.19
```

You can download a compiled binary from https://github.com/ethereum/solidity/releases.  Then either place the binary in you executable path, or set the `SOLC_BINARY` environmental variable with the path of the solc executable.

**Comment by ajax-2** [comment]
im a robot

**Comment by dylanjw** [comment]
#48

**Comment by TanviShrivastav** [comment]
I was trying to convert pdf to image and I also faced a similar error:

from pdf2image import convert_from_path, convert_from_bytes
import os
import tempfile

with tempfile.TemporaryDirectory() as path:
     images_from_path = convert_from_path('C:/Users/Intern4/Desktop/.pdf', output_folder=path)


FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-c5f9b37320a3> in <module>()
      2 
      3 with tempfile.TemporaryDirectory() as path:
----> 4      images_from_path = convert_from_path('C:/Users/Intern4/Desktop/.pdf', output_folder=path)

C:\ProgramData\Anaconda3\lib\site-packages\pdf2image\pdf2image.py in convert_from_path(pdf_path, dpi, output_folder, first_page, last_page, fmt, thread_count)
     26     """
     27 
---> 28     page_count = __page_count(pdf_path)
     29 
     30     if thread_count < 1:

C:\ProgramData\Anaconda3\lib\site-packages\pdf2image\pdf2image.py in __page_count(pdf_path)
    148 
    149 def __page_count(pdf_path):
--> 150     proc = Popen(["pdfinfo", pdf_path], stdout=PIPE, stderr=PIPE)
    151     out, _ = proc.communicate()
    152     try:

C:\ProgramData\Anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    707                                 c2pread, c2pwrite,
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:
    711             # Cleanup if the child failed starting.

C:\ProgramData\Anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    995                                          env,
    996                                          os.fspath(cwd) if cwd is not None else None,
--> 997                                          startupinfo)
    998             finally:
    999                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified

What is going wrong?

**Comment by ppLorins** [comment]
Same issue. solc is available in the commond line , but throws exceptions by this snippet  : 
```python
if not os.path.exists('solc'):
    raise FileNotFoundError("solc executable not found.  Is solc installed?")
```

Win7  solc:0.4.25+commit.59dbf8f1.Windows.msvc
