### ISSUE TITLE
solc.compile_source() Failed

### ISSUE THREAD

**Issue by ajax-2** [ethereum/py-solc#47]
* `py-solc` Version: 2.1.0
* `solc` Version: 0.4.21 (here is solcjs)
* Python Version: 3.5.4
* OS: linux(ubuntu)

### What was wrong?

Use compile_source(source) fail !!

My commands:

> Install solc:  npm install -g solc
Install py-solc: pip3 install py-solc
Use solc in python3:
  from solc import compile_source
  compile_source('pragma solidity ^0.4.0; contract A{ funcion A() public{}}')

Details:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/solc/main.py", line 106, in compile_source
    stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/solc/utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/solc/wrapper.py", line 165, in solc_wrapper
    stderr_data=stderrdata,
solc.exceptions.SolcError: An error occurred during execution
> command: `solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,userdoc`
> return code: `1`
> stderr:

> stdout:
Must provide a file

#### Cute Animal Picture

> put a cute animal picture here.
![animals-smile_3379238k](https://user-images.githubusercontent.com/29370146/38020552-24412b82-32ad-11e8-9ca2-3e9a5004584e.jpg)

**Comment by dylanjw** [comment]
There is a typo in your solidity snippet.  Missing the T in function.  Should be:

```
compile_source('pragma solidity ^0.4.0; contract A{ function A() public{}}')
```

**Comment by carver** [comment]
Although "Must provide a file" is a confusing error message for a failed computation.

**Comment by dylanjw** [comment]
Its possible that @ajax-2 hit another issue before hitting the syntax error.  When I ran the example snippet I got:

```
        <stdin>:1:46: Error: Expected token Semicolon got 'LParen'
pragma solidity ^0.4.0; contract A{ funcion A() public{}}
```

I am using the apt packaged solc. Im wondering if the version of solc installed by the npm package is different than the regular solc binary. I also thought that the npm solc command was "solcjs", which definitely does behave differently.

**Comment by ajax-2** [comment]
@dylanjw  I'm sorry that My contract's code is error. I know what does my problem cause. My solc is not complete, Because solcjs cannot adapt to py-solc. I uninstall my solcjs and install it with "apt-get install solc", now, I can use py-solc normally. thanks!! your reply is very useful!

**Comment by dylanjw** [comment]
Glad I could help!
