### ISSUE TITLE
Can't compile abi (issue with path and JSON logic exception)

### ISSUE THREAD

**Issue by j10sanders** [ethereum/py-solc#49]
* `py-solc` Version: 0.4.19
* `solc` Version: don't have?
* Python Version: 3.6.3
* OS: linux

### What was wrong?
Can't compile abi for this smart contract: https://gist.github.com/j10sanders/d85ded8810d20ff1368cae23f00a9732

Steps taken:
`python -m solc.install v0.4.19 /home/jonathan/virtualenvs/call/bin/python: No module named solc`
I set the environment variable: `SOLC_BINARY=$HOME/.py-solc/solc-v0.4.19/bin/solc`

```from solc.wrapper import get_solc_binary_path
get_solc_binary_path()
print(get_solc_binary_path) //solc
```

@pipermerriam was helping me in Gitter, and got me to a place where I can use solc, but it is using my absolute path.  This probably won't fly when I have to deploy this to heroku.
```
compiled_sol = compile_standard({'language': 'Solidity', 'sources': contract_source_code}, solc_binary="/home/jonathan/.py-solc/solc-v0.4.19/bin/solc")
```

```
solc.exceptions.SolcError: JSON logic exception: in Json::Value::getMemberNames(), value must be objectValue
> command: `/home/jonathan/.py-solc/solc-v0.4.19/bin/solc --standard-json`
> return code: `0`
> stderr:
{"errors":[{"component":"general","formattedMessage":"JSON logic exception: in Json::Value::getMemberNames(), value must be objectValue","message":"JSON logic exception: in Json::Value::getMemberNames(), value must be objectValue","severity":"error","type":"InternalCompilerError"}]}

> stdout:
```
I've tried this too:
```
with open('escrow.sol', 'r') as f:
	contract_source_code = f.read()
	compiled_sol = compile_standard({'language': 'Solidity', 'sources': {'escrow.sol': contract_source_code}}, solc_binary="/home/jonathan/.py-solc/solc-v0.4.19/bin/solc")
// "errors":[{"component":"general","formattedMessage":"Source input is not a JSON object.","message":"Source input is not a JSON object.","severity":"error","type":"JSONError"}]}
```
#### Cute Animal Picture

> My kitten Larry, this morning.
https://image.ibb.co/m1yWrx/larry.jpg

![My kitten, Larry, this morningt](https://image.ibb.co/m1yWrx/larry.jpg "My kitten this morning")

**Comment by pipermerriam** [comment]
Take a look at http://solidity.readthedocs.io/en/v0.4.19/using-the-compiler.html#compiler-input-and-output-json-description

Looks like your sources needs to be something like `{'escrow.sol': {'content': contract_source_code}}`.

**Comment by j10sanders** [comment]
Hi @pipermerriam , sorry, I just saw your comment!

That helped.  Can you help me determine how to get the abi from this?

```
with open('escrow.sol', 'r') as f:
	contract_source_code = f.read()
	compiled_sol = compile_standard({
		'language': 'Solidity',
		'sources': {'escrow.sol': {'content': contract_source_code}}},
		solc_binary="/home/jonathan/.py-solc/solc-v0.4.19/bin/solc")

print(compiled_sol)
// {'contracts': {'escrow.sol': {'Escrow': {'evm': {}}}}, 'sources': {'escrow.sol': {'id': 0}}}

escrow = w3.eth.contract(address='0x8850259566e9d03a1524e35687db2c78d4003409', abi=compiled_sol['contracts']['escrow.sol'])
// ValueError: Could not format value {'Escrow': {'evm': {}}} as field 'abi'
```

**Comment by j10sanders** [comment]
fixed with help from @pipermerriam

**Comment by j10sanders** [comment]
needed to downgrade to 0.4.17
