### ISSUE TITLE
Invalid option to --combined-json: clone-bin

### ISSUE THREAD

**Issue by flipchan** [ethereum/py-solc#61]
* `py-solc` Version: 3.0.0
* `solc` Version: 0.5.0
* Python Version: 3.5.3
* OS: Linux debian 9  

### What was wrong?

solc does not take the system argument "--combined-json" and returns an error 
"Invalid option to --combined-json: clone-bin"
```

tried like this: https://stackoverflow.com/questions/50238914/py-solc-and-solidity-imports

root@debian9:~dev/eth/# solc --version    
solc, the solidity compiler commandline interface                                    
Version: 0.5.0-develop.2018.10.17+commit.72b1bb00.mod.Linux.g++    

root@debian9:~dev/eth/# python3.5       
Python 3.5.3 (default, Sep 27 2018, 17:25:39)                                      
[GCC 6.3.0 20170516] on linux                                                      
Type "help", "copyright", "credits" or "license" for more information.             
>>> import os
>>> from solc import compile_files
>>> PROJECT_ROOT = os.getcwd()
>>> compiled_sol = compile_files([os.path.join(PROJECT_ROOT, "bar.sol"), os.path.join(PROJECT_
ROOT, "baz.sol")])                                                                            
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/solc/main.py", line 135, in compile_files
    stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/solc/utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/solc/wrapper.py", line 165, in solc_wrapper
    stderr_data=stderrdata,
solc.exceptions.SolcError: An error occurred during execution
> command: `solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcode
s,userdoc /root/dev/eth/bar.sol /root/dev/eth/`
> return code: `1`
> stderr:

> stdout:
Invalid option to --combined-json: clone-bin
```

**Comment by flipchan** [comment]
This was solved by compiling the branch v0.4.24 of solc , this was a pure solc error

**Comment by heysun0728** [comment]
Can you explain the solution in more detail? I got the same problem.

**Comment by flipchan** [comment]
yeah the solution was to compile another branch, i had the wrong solc version(run solc -version)

**Comment by flipchan** [comment]
use an offical stable release @heysun0728 https://github.com/ethereum/py-solc/releases

**Comment by ChristopherHolder** [comment]
Yeah , I am having the same problem. The thing is that py-solc is suppose to handle earlier 4.* solc versions.

**Comment by tabz11** [comment]
My code was working before then did install another software and it messed up settings for py-solc. I have tried everything in this blog, still same error. Please help.

**Comment by dbe** [comment]
From the patch notes of Solidity 5.0: [Link](https://solidity.readthedocs.io/en/latest/050-breaking-changes.html?highlight=clone-bin)

"The --clone-bin and --combined-json clone-bin command line options were removed.".


Seems like you will have to downgrade your solc version until py-solc changes it's use of --combined-json clone-bin.

**Comment by ihyf** [comment]
ubuntu how to install 0.4.25 solc?

**Comment by tabz11** [comment]
`python -m solc.install v0.4.25` further [see](https://pypi.org/project/py-solc/)

**Comment by flipchan** [comment]
u can simple solve it by getting a version 5< from https://github.com/ethereum/solidity/releases

**Comment by brunneis** [comment]
> * `py-solc` Version: 3.0.0
> * `solc` Version: 0.5.0
> * Python Version: 3.5.3
> * OS: Linux debian 9
> 
> ### What was wrong?
> solc does not take the system argument "--combined-json" and returns an error
> "Invalid option to --combined-json: clone-bin"
> 
> ```
> 
> tried like this: https://stackoverflow.com/questions/50238914/py-solc-and-solidity-imports
> 
> root@debian9:~dev/eth/# solc --version    
> solc, the solidity compiler commandline interface                                    
> Version: 0.5.0-develop.2018.10.17+commit.72b1bb00.mod.Linux.g++    
> 
> root@debian9:~dev/eth/# python3.5       
> Python 3.5.3 (default, Sep 27 2018, 17:25:39)                                      
> [GCC 6.3.0 20170516] on linux                                                      
> Type "help", "copyright", "credits" or "license" for more information.             
> >>> import os
> >>> from solc import compile_files
> >>> PROJECT_ROOT = os.getcwd()
> >>> compiled_sol = compile_files([os.path.join(PROJECT_ROOT, "bar.sol"), os.path.join(PROJECT_
> ROOT, "baz.sol")])                                                                            
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.5/dist-packages/solc/main.py", line 135, in compile_files
>     stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/solc/utils/string.py", line 85, in inner
>     return force_obj_to_text(fn(*args, **kwargs))
>   File "/usr/local/lib/python3.5/dist-packages/solc/wrapper.py", line 165, in solc_wrapper
>     stderr_data=stderrdata,
> solc.exceptions.SolcError: An error occurred during execution
> > command: `solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcode
> s,userdoc /root/dev/eth/bar.sol /root/dev/eth/`
> > return code: `1`
> > stderr:
> 
> > stdout:
> Invalid option to --combined-json: clone-bin
> ```

If you want to use the last version of `solc` you can give a try to the simple wrapper I've developed in order to avoid this problem. Tested with `solc 0.5.2+commit.1df8f40c`.

`easysolc` - https://github.com/brunneis/easysolc

**Comment by Chiheb-Nexus** [comment]
The solution to this problem is:
- Remove any solc version < 0.4.25: If you're using Debian/Ubuntu just run: `sudo apt-get remove solc`
- Under your `virtualenv` run: `pip install py-solc` then `python -m solc.install v0.4.25`
Now you've `solc` compiler installed under your: `$HOME/.py-solc/solc-v0.4.25/bin/solc`, all you need to do now is make `solc` available just by typing it's name in the terminal.
You nned to copy you're `solc` file to `/usr/bin` or `/usr/local/bin`: `cp $HOME/.py-solc/solc-v0.4.25/bin/solc /usr/local/bin/`

And you'll endup with the correct `solc` version and you'll not have this error.

**Comment by prographo** [comment]
Same problem.

python -m solc.install v0.4.25

bombs:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:789:5: note: candidate constructor not viable: requires at least 3 arguments, but 1 was provided
    basic_string(const basic_string& __str, size_type __pos, size_type __n,
    ^
2 errors generated.
make[2]: *** [libevmasm/CMakeFiles/evmasm.dir/Assembly.cpp.o] Error 1
make[1]: *** [libevmasm/CMakeFiles/evmasm.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code

However I was instead able to change py-solc according to these instructions:

https://github.com/Jonasmpi/py-solc/commit/88cdaeb10eff79c07a502d0333893a66d59f575f

Which seems to work.
