### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'solc'

### ISSUE THREAD

**Issue by wangyuncong123** [ethereum/py-solc#72]
* `py-solc` Version: x.x.x
* `solc` Version: x.x.x
* Python Version: x.x.x
* OS: linux

### What was wrong?

i'm using the buildozer to build a apk,i needed solc in the android phone,

my buildozer requirements = python3,kivy,web3,eth-account==0.3.0,cytoolz,setuptools,toolz,ethereum,eth-keyfile,pycryptodome,eth-keys,eth-utils,eth-hash,eth-typing,hexbytes,eth-rlp,rlp,attrdict,eth-abi,parsimonious,idna,lru-dict,requests,websockets,**py-solc**,semantic_version

my error log is
05-26 13:04:01.696 16531 16554 I python  : Initializing Python for Android
05-26 13:04:01.696 16531 16554 I python  : Setting additional env vars from p4a_env_vars.txt
05-26 13:04:01.696 16531 16554 I python  : Changing directory to the one provided by ANDROID_ARGUMENT
05-26 13:04:01.696 16531 16554 I python  : /data/user/0/org.test.myapp/files/app
05-26 13:04:01.697 16531 16554 I python  : Preparing to initialize python
05-26 13:04:01.697 16531 16554 I python  : _python_bundle dir exists
05-26 13:04:01.697 16531 16554 I python  : calculated paths to be...
05-26 13:04:01.697 16531 16554 I python  : /data/user/0/org.test.myapp/files/app/_python_bundle/stdlib.zip:/data/user/0/org.test.myapp/files/app/_python_bundle/modules
05-26 13:04:01.698 16531 16554 I python  : set wchar paths...
05-26 13:04:01.847 16531 16554 I python  : Initialized python
05-26 13:04:01.847 16531 16554 I python  : AND: Init threads
05-26 13:04:01.850 16531 16554 I python  : testing python print redirection
05-26 13:04:01.853 16531 16554 I python  : Android path ['.', '/data/user/0/org.test.myapp/files/app/_python_bundle/stdlib.zip', '/data/user/0/org.test.myapp/files/app/_python_bundle/modules', '/data/user/0/org.test.myapp/files/app/_python_bundle/site-packages']
05-26 13:04:01.854 16531 16554 I python  : os.environ is environ({'PATH': '/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin', 'DOWNLOAD_CACHE': '/data/cache', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOINT': '/mnt/asec', 'BOOTCLASSPATH': '/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/bouncycastle.jar:/system/framework/apache-xml.jar:/system/framework/legacy-test.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/android.hidl.base-V1.0-java.jar:/system/framework/android.hidl.manager-V1.0-java.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-telephony-common.jar:/system/framework/mediatek-telephony-base.jar:/system/framework/mediatek-ims-common.jar:/system/framework/mediatek-telecom-common.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar', 'ANDROID_SOCKET_zygote': '8', 'ANDROID_ENTRYPOINT': 'main.pyc', 'ANDROID_ARGUMENT': '/data/user/0/org.test.myapp/files/app', 'ANDROID_APP_PATH': '/data/user/0/org.test.myapp/files/app', 'ANDROID_PRIVATE': '/data/user/0/org.test.myapp/files', 'ANDROID_UNPACK': '/data/user/0/org.test.myapp/files/app', 'PYTHONHOME': '/data/user/0/org.test.myapp/files/app', 'PYTHONPATH': '/data/user/0/org.test.myapp/files/app:/data/user/0/org.test.myapp/files/app/lib', 'PYTHONOPTIMIZE': '2', 'P4A_BOOTSTRAP': 'SDL2', 'PYTHON_NAME': 'python', 'P4A_IS_WINDOWED': 'True', 'P4A_ORIENTATION': 'portrait', 'P4A_NUMERIC_VERSION': 'None', 'P4A_MINSDK': '21', 'LC_CTYPE': 'C.UTF-8'})
05-26 13:04:01.854 16531 16554 I python  : Android kivy bootstrap done. __name__ is __main__
05-26 13:04:01.854 16531 16554 I python  : AND: Ran string
05-26 13:04:01.854 16531 16554 I python  : Run user program, change dir and execute entrypoint
05-26 13:04:02.279 16531 16554 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.test.myapp/files/app/.kivy/logs/kivy_19-05-26_2.txt
05-26 13:04:02.280 16531 16554 I python  : [INFO   ] [Kivy        ] v1.11.0.dev0, git-Unknown, 20190524
05-26 13:04:02.281 16531 16554 I python  : [INFO   ] [Python      ] v3.7.1 (default, May 25 2019, 02:03:11) 
05-26 13:04:02.281 16531 16554 I python  : [Clang 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55
05-26 13:04:04.571 16531 16554 I python  : [INFO   ] [Factory     ] 184 symbols loaded
05-26 13:04:05.689 16531 16554 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
05-26 13:04:12.989 16531 16554 I python  :  Traceback (most recent call last):
05-26 13:04:12.990 16531 16554 I python  :    File "/home/wyc/.buildozer/android/app/main.py", line 55, in <module>
05-26 13:04:12.992 16531 16554 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/solc/main.py", line 108, in compile_source
05-26 13:04:12.994 16531 16554 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/solc/utils/string.py", line 85, in inner
05-26 13:04:12.996 16531 16554 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/solc/wrapper.py", line 159, in solc_wrapper
05-26 13:04:12.998 16531 16554 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Lib/subprocess.py", line 769, in __init__
05-26 13:04:13.000 16531 16554 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Lib/subprocess.py", line 1516, in _execute_child
05-26 13:04:13.001 16531 16554 I python  :  PermissionError: [Errno 13] Permission denied: 'solc'
05-26 13:04:13.002 16531 16554 I python  : Python for android ended.

why there is a permissionerror?

#### Cute Animal Picture
![图片](https://user-images.githubusercontent.com/49501638/58377752-78e27200-7fc2-11e9-99ce-25774bf195cd.png)

**Comment by oldnote** [comment]
Best animal picture ever.

**Comment by abhishekgujarathi** [comment]
Are you trying to use solc on android in termux?
