### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'solc': 'solc'

### ISSUE THREAD

**Issue by ghost** [ethereum/py-solc#73]
FileNotFoundError: [Errno 2] No such file or directory: 'solc': 'solc'

**Comment by MatthiasLohr** [comment]
You need to install the solc compiler.

**Comment by davesque** [comment]
I believe that's probably the issue.  Also, this library is not well-supported nowadays.  In fact, I believe it's deprecated.  Any errors occurring could well be a result of that.  I'll close this for now.  Feel free to re-open if you have more comments/concerns.

**Comment by MatthiasLohr** [comment]
Is there any official replacement for this library?

**Comment by davesque** [comment]
I don't believe so.  Part of the reason for deprecation is that it was decided that Solidity's command-line API is too much of a moving target.

**Comment by iamdefinitelyahuman** [comment]
@MatthiasLohr I'm maintaining an unofficial fork - [py-solc-x](https://github.com/iamdefinitelyahuman/py-solc-x)

**Comment by MatthiasLohr** [comment]
@iamdefinitelyahuman Thanks for this link!
